name: Deploy via Pelican on GitHub pages

on:
  push:
    branches:
      - main

jobs:
  pelican:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: rehanhaider/pelican-to-github-pages@latest
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: cyberape.space